project:
  type: website
  output-dir: docs

website:
  title: "Jiadong Mao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: invited.qmd
        text: Talks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

