project:
  type: website
  output-dir: docs

website:
  title: "Jiadong Mao"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: publications.qmd
        text: "Publications"
      - text: "Talks"
        href: invited.qmd
      - text: "Random thoughts"
        href: blog/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

