---
title: "Talks & workshops"
---

[Selected Talk](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/Mao_StatsLeadership.pdf): I’m (not) just a statistician: Working in multidisciplinary research as an ECR. Melbourne & Brisbane, July 2026

[Seminar](https://events.unimelb.edu.au/MIG/event/52380-mig-special-seminar-dr-jiadong-mao-university-of): From phenotypes to molecular drivers: finding cell states and mechanistic insights in omics data. Melbourne, June 2026

[Workshop](https://events.unimelb.edu.au/safes/event/51256-mig-workshop-advanced-methods-for-scrna-seq-data): MIG Workshop: Advanced methods for scRNA-seq data. Melbourne, May 2026

Invited talk: DIVAS: finding shared and individual variation in multimodal data. ANU (online), May 2026

[Journal Club](https://github.com/jiadongm/FactorIV-MicrobialMethodsJournalClub): Factor IV: instrumental variable factor analysis for causal inference in microbiome data. Melbourne, April 2026

[Workshop](https://github.com/jiadongm/EBNMF-workshop): Empirical Bayes Matrix Factorisation. Melbourne, March 2026

Invited talk: Rheumatoid Arthritis Annual Meeting, Brisbane, Feb 2026

[Invited talk](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/JiadongMao_DIVAS_pdf.pdf): Integrating ≥3 omics using DIVAS. MIG Symposium 2025.

Invited talk: $\Phi$-Space for cell states discovery in single-cell and spatial omics data. Peter Doherty Institute, Jul 2025.

[Invited talk](https://www.birs.ca/events/2025/5-day-workshops/25w5391/videos/watch/202506161420-Mao.html) at Workshop: Spatial Omics -- Integrating Biotechnologies, Methodologies and Applications, Hangzhou, China, June 2025.

[Selected talk](https://www.wehi.edu.au/event/wehi-spatial-technology-symposium/) at WEHI Spatial Technology Symposium, Melbourne, June 2025.

[From biology to statistics, and back](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/RMIT_guestLecture_Apr2025.pdf). Guest lecture at RMIT University, Apr 2025.

[Embracing instability: Assessing stability of variables via StableMate](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/StableMate_PublicHealth.pdf). Breast Cancer Unit & Twin Research Australia, Melbourne School of Population & Global Health, Apr 2025

[PhiSpace ST for spatial biology discovery](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/PhiSpaceST_MIG_seminar.pdf). Australian BioCommons (online), Mar 2025; Murdoch Children's Research Institute, March 2025; Melbourne Integtative Genomics Monthly Seminar. Feb 2025

[A tale of two spaces (poster)](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/Lorne2025-Posters-JiadongMao.pdf). Lorne Genome 2025.

PhiSpace for inferring cell differentiation trajectory. Oz Single Cell Hackthon, Sydney, Dec 2024

[Generative deep learning models for scRNA-seq data analysis](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/GenAI_scRNA-seq_4Dec_AMSI_BIS.pdf). AMSI BioInfoSummer, Melbourne, Dec 2024

[What's so special about spatial transcriptomics?](https://github.com/jiadongm/jiadongm.github.io/blob/main/slides/SchoolColloquiumSpatial.pdf) UniMelb School of Mathematics and Statistics Colloquium. Jun 2024
